
model_path: ./VERSPM
model_archive: ~/vision-eval/VisionEval-Archive
model_source: ~/vision-eval/VisionEval-Dev/built/visioneval/4.0.3/runtime/models/VERSPM

rel_output_path: ./output
r_library_path: ~/vision-eval/VisionEval-Dev/built/visioneval/4.0.3/ve-lib
r_runtime_path: ~/vision-eval/VisionEval-Dev/built/visioneval/4.0.3/runtime
